name: Bug Report
description: File a bug report.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

        ### Before you fill out this form...

        * The bug must be present in the core webview library and not caused by faults in language bindings.
        * The bug may have been fixed already—please test a newer version or the latest unreleased code (`master`/`main` branch).
  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: With which backend did you experience the bug?
      multiple: false
      options:
        - WebKit/Cocoa
        - WebKit2GTK/GTK3
        - WebView2/Win32
      default: 2
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug, the expected behavior and what happens instead.
      placeholder: >
        Example: Changing the display DPI scaling while my app is running makes the window grow in size regardless of what the scaling is set to.
        I would expect that changing the scaling from 200% to 100% would scale down the window, but instead it scales up!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      placeholder: |
        1. First step.
        2. Second step.
        3. ...
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: If you have a short code sample (C/C++) for reproducing the bug then please provide it.
      render: cpp
    validations:
      required: false
  - type: input
    id: code-sample-url
    attributes:
      label: External code sample
      description: If you have an external code sample (C/C++) for reproducing the bug then please provide the URL.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Describe your system's environment such as the operating system and compiler. Feel free to provide the output of the following commands.

        Unix-like:
        ```
        echo "OS: $(( (if command -v sw_vers &> /dev/null; then echo "$(sw_vers -productName) $(sw_vers -productVersion)"; else lsb_release -sd 2>/dev/null; fi) || echo Unknown) | tr -d '\n') ($(uname -m))"
        echo "GCC: $((gcc --version 2>/dev/null || echo N/A) | head -n1)"
        echo "Clang: $((clang --version 2>/dev/null || echo N/A) | head -n1)"
        ```

        Windows (PowerShell):
        ```
        "OS: $($os = Get-CimInstance Win32_OperatingSystem; if (-not ($a = $env:PROCESSOR_ARCHITEW6432)) { $a = $env:PROCESSOR_ARCHITECTURE }; "$($os.Caption) $($os.Version) ($a)")",
        "GCC: $(if (Get-Command gcc -CommandType Application -ErrorAction SilentlyContinue) { &gcc --version | select -First 1 } else { "N/A" })",
        "Clang: $(if (Get-Command clang -CommandType Application -ErrorAction SilentlyContinue) { &clang --version | select -First 1 } else { "N/A" })",
        "WebView2 Runtime: $(if ($p = Get-ItemProperty -Path "HKLM:\SOFTWARE\$(if ([Environment]::Is64BitOperatingSystem) { "WOW6432Node\" } else {})Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" -ErrorAction SilentlyContinue) { $p.pv } else { "N/A" })" `
        | %{ $_ }
        ```
      placeholder: |
        OS: Ubuntu 22.04.3 LTS (x86_64)
        GCC: gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
        Clang: Ubuntu clang version 14.0.0-1ubuntu1.1
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any additional context about the bug such as screenshots.
    validations:
      required: false
