name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
#projects: ['octo-org/1', 'octo-org/44']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what happened instead of the above.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce the bug?
      description: Describe the steps to reproduce the bug.
      value: |
        1. Step
        2. Step
        3. Step
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: If you have a short code sample (C/C++) for reproducing the bug then please provide it.
      render: cpp
      value: |
        #include "webview.h"
        #include <stddef.h>

        static const char html[] =
            "<button id=\"tap\">Tap me</button>\n"
            "<script>\n"
            "  const tapElement = document.querySelector(\"#tap\");\n"
            "  document.addEventListener(\"DOMContentLoaded\", () => {\n"
            "    tapElement.addEventListener(\"click\", () => {\n"
            "      tap().then(result => {\n"
            "        // TODO\n"
            "      });\n"
            "    });\n"
            "  });\n"
            "</script>";

        void on_tapped(const char *seq, const char *req, void *arg) {
          webview_t w = (webview_t)arg;
          webview_return(w, seq, 0, "");
        }

        int main() {
          webview_t w = webview_create(0, NULL);
          webview_set_title(w, "Example");
          webview_set_size(w, 480, 320, WEBVIEW_HINT_NONE);
          webview_bind(w, "tap", on_tapped, w);
          webview_set_html(w, html);
          webview_run(w);
          webview_destroy(w);
          return 0;
        }
    validations:
      required: false
  - type: input
    id: code-sample-url
    attributes:
      label: External code sample
      description: If you have an external code sample for reproducing the bug then please provide the URL.
    validations:
      required: false
  - type: checkboxes
    id: applies-to-core
    attributes:
      label: Does the bug apply to the core webview library?
      description: The bug must be in the core library and not in e.g. language bindings.
      options:
        - label: The bug is present in the core library.
          required: true
  - type: input
    id: affected-versions
    attributes:
      label: Affected versions
      description: The released version(s) affected by the bug if any. Separate each affected version by a comma and space.
      placeholder: x.y.z
    validations:
      required: false
  - type: checkboxes
    id: applies-to-unreleased-code
    attributes:
      label: Is the latest unreleased code affected?
      description: The bug may have been fixed already—please test the latest unreleased code (master/main branch).
      options:
        - label: The bug is present in the latest unreleased code.
          required: true
  - type: input
    id: binding-language
    attributes:
      label: 'Binding: Language'
      description: Name of language if you're using a language binding.
    validations:
      required: false
  - type: input
    id: binding-url
    attributes:
      label: 'Binding: Language'
      description: URL of language binding if applicable.
    validations:
      required: false
  - type: dropdown
    id: device-platform
    attributes:
      label: Platform
      description: Select your platform.
      multiple: false
      options:
        - BSD
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: dropdown
    id: device-architecture
    attributes:
      label: Architecture
      description: Select the your processor architecture.
      options:
        - Intel x86 (i686)
        - AMD64 (x86_64)
        - ARM32 (AArch32)
        - ARM64 (AArch64)
        - Other
    validations:
      required: true
  - type: dropdown
    id: target-platform
    attributes:
      label: Target platform
      description: Select the target platform.
      multiple: false
      options:
        - BSD
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: dropdown
    id: target-architecture
    attributes:
      label: Target architecture
      description: Select the target architecture.
      options:
        - Same as device
        - Intel x86 (i686)
        - AMD64 (x86_64)
        - ARM32 (AArch32)
        - ARM64 (AArch64)
        - Other
    validations:
      required: true
  - type: input
    id: device-system-linux-distro
    attributes:
      label: 'Linux: Distribution-specific information'
      description: Paste the output of `lsb_release -sd` if applicable.
  - type: input
    id: device-system-unix-info
    attributes:
      label: 'Unix: System information'
      description: Paste the output of `uname -a` if applicable.
  - type: input
    id: device-system-windows
    attributes:
      label: 'Windows: System information'
      description: Paste the output of `(Get-CimInstance Win32_OperatingSystem).Version` (PowerShell) if applicable.
