name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
#projects: ['octo-org/1', 'octo-org/44']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: behavior
    attributes:
      label: What happened?
      description: Describe the bug in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expected to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How can we reproduce the bug?
      description: Describe the steps to reproduce the bug.
    validations:
      required: true
  - type: input
    id: affected-version
    attributes:
      label: Affected version
      description: The released version that is affected by the bug if any.
      placeholder: x.y.z
    validations:
      required: false
  - type: checkboxes
    id: applies-to-unreleased-code
    attributes:
      label: Is the latest unreleased code affected?
      description: The bug may have been fixed already—please test the latest unreleased code (master/main branch).
      options:
        - label: The bug is present in the latest unreleased code.
          required: true
  - type: dropdown
    id: affected-platform
    attributes:
      label: Platform
      description: Select your platform.
      multiple: false
      options:
        - BSD
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: input
    id: device-system-unix-distro
    attributes:
      label: 'Unix: Distribution-specific information'
      description: Paste the output of `lsb_release -sa` if applicable.
  - type: input
    id: device-system-unix-info
    attributes:
      label: 'Unix: System information'
      description: Paste the output of `uname -a`.
  - type: input
    id: device-system-windows
    attributes:
      label: 'Windows: System information'
      description: Paste the output of `(Get-CimInstance Win32_OperatingSystem).Version` (PowerShell).
