name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
#projects: ['octo-org/1', 'octo-org/44']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: where-bug-applies
    attributes:
      label: Where did you see the bug?
      description: |
        * The bug must be present in the core webview library and not caused by faults in language bindings.
        * The bug may have been fixed already—please test the latest unreleased code (master/main branch).
      options:
        - label: Saw the bug in the core webview library.
          required: true
        - label: Saw the bug in the latest unreleased code.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what happened instead of the above.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce the bug?
      description: Describe the steps to reproduce the bug.
      value: |
        1. Step
        2. Step
        3. Step
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: If you have a short code sample (C/C++) for reproducing the bug then please provide it.
      render: cpp
    validations:
      required: false
  - type: input
    id: code-sample-url
    attributes:
      label: External code sample
      description: If you have an external code sample (C/C++) for reproducing the bug then please provide the URL.
    validations:
      required: false
  - type: dropdown
    id: device-platform
    attributes:
      label: Device platform
      description: Select the platform running on your device.
      multiple: false
      options:
        - BSD
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: input
    id: device-platform-other
    attributes:
      label: Other device platform
      description: Name the platform running on your device if you chose "Other".
    validations:
      required: false
  - type: dropdown
    id: device-architecture
    attributes:
      label: Device architecture
      description: Select your device's processor architecture.
      options:
        - Intel x86 (i686)
        - AMD64 (x86_64)
        - ARM32 (AArch32)
        - ARM64 (AArch64)
        - Other
    validations:
      required: true
  - type: input
    id: device-architecture-other
    attributes:
      label: Other device architecture
      description: Name your device's processor architecture if you chose "Other".
    validations:
      required: false
  - type: dropdown
    id: target-platform
    attributes:
      label: Target platform
      description: Select the target platform.
      multiple: false
      options:
        - Same as device
        - BSD
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: input
    id: target-platform-other
    attributes:
      label: Other target platform
      description: Name the target platform if you chose "Other".
    validations:
      required: false
  - type: dropdown
    id: target-architecture
    attributes:
      label: Target architecture
      description: Select the target architecture.
      options:
        - Same as device
        - Intel x86 (i686)
        - AMD64 (x86_64)
        - ARM32 (AArch32)
        - ARM64 (AArch64)
        - Other
  - type: input
    id: target-architecture-other
    attributes:
      label: Other target architecture
      description: Name the target processor architecture if you chose "Other".
    validations:
      required: false
    validations:
      required: true
  - type: input
    id: device-system-linux-distro
    attributes:
      label: 'Linux: Distribution-specific information'
      description: Paste the output of `lsb_release -sd` if applicable.
  - type: input
    id: device-system-unix-info
    attributes:
      label: 'Unix: System information'
      description: Paste the output of `uname -a` if applicable.
  - type: input
    id: device-system-windows
    attributes:
      label: 'Windows: System information'
      description: Paste the output of `(Get-CimInstance Win32_OperatingSystem).Version` (PowerShell) if applicable.
