name: Feature Request
description: Suggest an idea for this project
labels: ['enhancement', 'triage']
#projects: ['octo-org/1', 'octo-org/44']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!

        ### Before you fill out this form...

        * The feature request must be rooted in the core webview library and not only in specific language bindings.
        * The feature may have been requested already—please search first.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Help us understand the problem(s) that would be solved by implementing the requested feature.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Desired solution
      description: If you have any solutions in mind already, we'll take your suggestions into consideration.
    validations:
      required: false
  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Select a backend for which you would like to see the feature implemented. We may prioritize your selected backend.
      multiple: false
      options:
        - WebKit/Cocoa
        - WebKit2GTK/GTK3
        - WebView2/Win32
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any additional context about the feature request such as screenshots.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Checklist

        <form>
          <fieldset>
            <div><label><input type="checkbox" /> The feature request is rooted in the core webview library.</label</div>
            <div><label><input type="checkbox" /> I checked and couldn't find an existing feature request.</label</div>
          </fieldset>
        </form>
